<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<!-- Windows Media Player COM -->
		<COMReference Include="WMPLib">
			<Guid>{6BF52A52-394A-11D3-B153-00C04F79FAA6}</Guid>
			<VersionMajor>1</VersionMajor>
			<VersionMinor>0</VersionMinor>
			<Lcid>0</Lcid>
			<WrapperTool>tlbimp</WrapperTool>
			<Isolated>false</Isolated>
		</COMReference>
		<COMReference Include="WMPLib">
		  <WrapperTool>tlbimp</WrapperTool>
		  <VersionMinor>0</VersionMinor>
		  <VersionMajor>1</VersionMajor>
		  <Guid>6bf52a50-394a-11d3-b153-00c04f79faa6</Guid>
		  <Lcid>0</Lcid>
		  <Isolated>false</Isolated>
		  <EmbedInteropTypes>true</EmbedInteropTypes>
		</COMReference>
		<COMReference Include="MediaPlayer">
		  <WrapperTool>tlbimp</WrapperTool>
		  <VersionMinor>0</VersionMinor>
		  <VersionMajor>1</VersionMajor>
		  <Guid>22d6f304-b0f6-11d0-94ab-0080c74c7e95</Guid>
		  <Lcid>0</Lcid>
		  <Isolated>false</Isolated>
		  <EmbedInteropTypes>true</EmbedInteropTypes>
		</COMReference>
		<COMReference Include="WMPNSSCI">
		  <WrapperTool>tlbimp</WrapperTool>
		  <VersionMinor>0</VersionMinor>
		  <VersionMajor>1</VersionMajor>
		  <Guid>453e9e02-8ba4-474c-bfa0-37727e44f6ae</Guid>
		  <Lcid>0</Lcid>
		  <Isolated>false</Isolated>
		  <EmbedInteropTypes>true</EmbedInteropTypes>
		</COMReference>
		<COMReference Include="WMPNSSCDS">
		  <WrapperTool>tlbimp</WrapperTool>
		  <VersionMinor>0</VersionMinor>
		  <VersionMajor>1</VersionMajor>
		  <Guid>73c381a8-548c-49f8-8ad3-c845d12d3c22</Guid>
		  <Lcid>0</Lcid>
		  <Isolated>false</Isolated>
		  <EmbedInteropTypes>true</EmbedInteropTypes>
		</COMReference>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>